[SUBMISSION] MODULE 1
huggingface/smol-course pull request #112
Opened 2024-12-16 17:03 UTC by Knight7561

# December 2024 Student Submission

## Module Completed
- [ ] Module 1: Instruction Tuning
- [ ] Module 2: Preference Alignment
- [ ] Module 3: Parameter-efficient Fine-tuning
- [ ] Module 4: Evaluation
- [ ] Module 5: Vision-language Models
- [ ] Module 6: Synthetic Datasets
- [ ] Module 7: Inference
- [ ] Module 8: Deployment

## Changes Made
Describe what you've done in this PR:
1. What concepts did you learn?
2. What changes or additions did you make?
3. Any challenges you faced?

## Notebooks Added/Modified
List any notebooks you've added or modified:
- [ ] Added new example in `module_name/student_examples/my_example.ipynb`
- [ ] Modified existing notebook with additional examples
- [ ] Added documentation or comments

## Checklist

- [ ] I have read the module materials
- [ ] My code runs without errors
- [ ] I have pushed models and datasets to the huggingface hub
- [ ] My PR is based on the `december_2024` branch

## Questions or Discussion Points
Add any questions you have or points you'd like to discuss:
1. 
2. 

## Additional Notes
Any other information that might be helpful for reviewers:

2024-12-18 08:41 UTC, burtenshaw commented
Structurally this looks great. 

@ShankarChavan Could you peer-review the notebooks please?

2024-12-20 03:40 UTC, Knight7561 commented
@burtenshaw @ShankarChavan Is my PR good ?

2024-12-20 06:15 UTC, ShankarChavan requested changes
In your **SFT_finetuning_example** the model has not shown any improvement on loss function. Also, the response from model for the given test-questions were giving repeated response as model has not learned yet. Please try to fix these issues from your end.

2025-01-08 04:06 UTC, burtenshaw approved these changes
Nice work @Knight7561

2025-01-08 04:06 UTC, merged